CLASSES=\
	jpe.header.Header	\
	jpe.header.ImageDataDirectory	\
	jpe.header.ImageDOSHeader	\
	jpe.header.ImageFileHeader	\
	jpe.header.ImageNTHeaders	\
	jpe.header.ImageOptionalHeader	\
	jpe.header.ImageOptionalHeader32	\
	jpe.header.ImageOptionalHeader64	\
	jpe.header.ImageSectionHeader	\
	jpe.intf.Characteristics	\
	jpe.intf.DLLCharacteristics	\
	jpe.intf.tree.IForest	\
	jpe.intf.tree.INode	\
	jpe.intf.tree.ITree	\
	jpe.resource.ImageResourceDataEntry	\
	jpe.resource.ImageResourceDirectory	\
	jpe.resource.ImageResourceDirectoryEntry	\
	jpe.resource.Types	\
	jpe.resource.version.StringFileInfo	\
	jpe.resource.version.StringStructure	\
	jpe.resource.version.StringTable	\
	jpe.resource.version.Var	\
	jpe.resource.version.VarFileInfo	\
	jpe.resource.version.VsFixedFileInfo	\
	jpe.resource.version.VsVersionInfo	\
	jpe.test.PE	\
	jpe.util.LanguageConstants	\
	jpe.util.tree.Forest	\
	jpe.util.tree.Node	\
	jpe.util.tree.Tree	\
	jpe.util.tree.TreeHash	\
	jpe.util.Version
